// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "father":return img`
......777777777.......
....77ccccccccc77.....
...7ccccccccccccc7....
..7ccccccffffffffc7...
.7ccccccfffffffffcc7..
.7ccccccfffffffcccc7..
7cccccccfdddffcccccc7.
7ccccccfddddfccccccc7.
7cccccfffddffccccccc7.
7ccccfffffffffcccccc7.
7cccffffeeeffffccccc7.
7cccfcffeeeffcfccccc7.
7cccfcffeeeffcfccccc7.
7cccdcffeeeffcdccccc7.
7cccccffffffcccccccc7.
.7ccccffccffccccccc7..
.7ccccffccffccccccc7..
..7cccddccddcccccc7...
...7ccdddcdddcccc7....
....77ccccccccc77.....
......777777777.......
......................
`;
            case "image2":
            case "myImage":return img`
................................
................................
................................
........ffffffffffffffffff......
.......fcccccccccccccccccf......
.......fcbffffbbbbbffffbcf......
.......fcbf16fbbbbbf61fbbcf.....
.......fcbf66fbbbbbf66fbbcf.....
.......fcbffffbbbbbffffbbcf.....
.......fcbbbbbbbbbbbbbbbbcf.....
.......fcbbbbbbbbbbbbbbbbcf.....
.......fcbbbbbffffbbbbbbbcf.....
.......fccccccccc9ccccccccf.....
.......ffffffffff9fffffffff.....
............fcbbbbbf.....ff.....
..........ffffffffff.ff.........
..fffffffffccccccccffffffffffff.
..fccbbbbbfcbbbbbbbbbbfccbbbbbf.
..fffffffffcbbbbbbbbbbfffffffff.
..........fcbbbbbbbbbbff........
..........fcbbbbbbbbbbf.........
..........fcbbbbbbbbbbf.........
...........fcbbbbbbbbbf.........
...........fcccbbbbbbbf.........
...........fffffffffff..........
.............fcf..fcf...........
.............fcf..fcf...........
.............fcf..fbf...........
.............fbf..fbf...........
.............fbf..fbf...........
.............fbf..fbf...........
.............fff..fff...........
`;
            case "image3":
            case "work":return img`
. . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . 
. f . . . f . . . . . . . . . . . . 
. f . . . f . . . . . . . . f . . f 
. f . . . f . . . . . . . . f . f . 
. f . . . f . f f f . f f . f f . . 
. f . f . f . f . f . f . . f . f . 
. f f f f f . f f f . f . . f . . f 
. . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . 
`;
            case "image4":
            case "stress":return img`
. . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . 
. . . f . . . . . . . . . . . . . . . 
. . f . . . . . . . . . . . . . . . . 
. f . . . f . . . . . . . . . . . . . 
. . f . f f f . . . . f f . . f . . f 
. . . f . f . . f f . f f . f . . f . 
. . f . . f . . f . . f . . . f . . f 
. f . . . f f . f . . f f . f . . f . 
. . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "mySong":return hex`0078000408020106001c00010a006400f4016400000400000000000000000000000000000000024e0000000400012708000c00012410001400012018001c00012c1c002000012c20002400012c24002800012c28002c0001272c003000012730003400012034003800012038003c0001243c0040000127`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
